baseurl = "https://salekseev.com/" # Hostname (and path) to the root.
title = "~salekseev" # Site title.
theme = "coder" # Set the theme.
languagecode = "en-us" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "paraiso-dark" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

disqusShortname = "salekseev-com" # Enable or disable Disqus

[params] # theme parameters
    author = "Stas Alekseev" # Author's name.
    info = "Full Stack DevOps and Magician" # Author's job title or info.
    description = "Stas Alekseev's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.png" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "© Stas Alekseev, 2014 - 2018"

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/salekseev/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/stas.alekseev/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/salekseev/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
